name: Create new release with changelog and partial semver tags

permissions:
  contents: write
  pull-requests: write

on:
  pull_request_target:
    types: [closed]

jobs:
  release:
    uses: timkrebs/github-workflows/.github/workflows/gh-create-release.yml@main

  partial_semver_tags:
    needs: release
    uses: timkrebs/github-workflows/.github/workflows/gh-partial-semver-tags.yml@main
